import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ashtail, AshtailWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :ashtail, AshtailWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Kafka connection defaults, overridable by KAFKA_* environment variables.
# `brokers: :required` makes `Config.resolve!/0` raise at boot if
# KAFKA_BROKERS is not set, the way SECRET_KEY_BASE already does.
config :ashtail, :kafka_defaults,
  brokers: :required,
  client_id: "ashtail",
  connect_timeout: 10_000,
  request_timeout: 30_000,
  tls: true,
  sasl_mechanism: nil,
  sasl_username: nil,
  sasl_password: nil

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
